pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Seth Hendrick
title: Seth's Activity Pub Bots!
description: "Bots that follow the Activity Pub protocol written by Seth Hendrick"
url: https://activitypub.shendrick.net/
urlnohttp: activitypub.shendrick.net
contact: seth@shendrick.net
enable_subcategories: false
github: https://github.com/xforever1313/activitypub.shendrick.net

clockbotservice: /clockbots

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .cake
 - Readme.md
